language: groovy

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  
before_script:
  - psql -c 'create database testCI_test;' -U postgres
  
script: ./grailsw refresh-dependencies
     && ./grailsw test-app
