language: groovy

jdk:
  - oraclejdk7

before_script:
  - psql -c 'create database testCI_test;' -U postgres

before_install:
  - curl -s get.gvmtool.net | bash
  - gvm help
  - sudo add-apt-repository -y ppa:groovy-dev/grails
  - sudo apt-get update
  - sudo apt-get install grails-ppa

script: grails refresh-dependencies
     && grails test-app
