language: groovy

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  
before_script:
  - psql -c 'create database testCI_test;' -U postgres
  
before_install:
  - sudo add-apt-repository -y ppa:groovy-dev/grails
  - sudo apt-get update
  - sudo apt-get install grails-2.1.1
  
script: ./grailsw refresh-dependencies
     && ./grailsw test-app
